### ISSUE TITLE
Losing many reads after polyA filtering "no polyT"

### ISSUE THREAD

**Issue by ngualand** [singleron-RD/CeleScope#144]
Good Morning, 

I notice that the step of reads filtering removes a high number of reads due to "no polyT" so that the "no polyT reads number" is very high. Can you explain this and suggest how can I fix it?

Many thanks

**Comment by zhouyiqi91** [comment]
Following the UMI, a poly(T) tail is expected. Each read is kept for further consideration only if ≥10 out of 18 bases at the specified positions are found to be Ts.

You can add `--allowNoPolyT` to `multi_{assay}` or `celescope {assay} barcode` to bypass this filtering.

**Comment by ngualand** [comment]
Thank you for the answer,

So the results that I obtain mean that in the experiment analyzed there are many reads that do not have the polyT tract?
Is this why the software removes them? 
Can be correct to add the option --allowNoPolyT and avoid the filter or this will leads to downstream errors?

**Comment by zhouyiqi91** [comment]
> So the results that I obtain mean that in the experiment analyzed there are many reads that do not have the polyT tract?

Yes.

> Is this why the software removes them?

Yes.

> Can be correct to add the option --allowNoPolyT and avoid the filter or this will leads to downstream errors?

Adding `--allowNoPolyT` will not lead to downstream errors.

**Comment by ngualand** [comment]
Thank you, 

Solved.

**Comment by zhou-ran** [comment]
Hi all,

Actually, missing polyT tail at R1 doesn't mean it's an useless read. Because most of users generated their scRNA-seq data from genome sequencing companies, and these companies will process the similar libraries at same sequencing machine  for convenience. 

As we know, the R1 reads showed an enrichment of T in 3' based scRNA-seq library, and the imbalance of base will be amplified if we sequenced multiple 3' based scRNAseq libraries simultaneously. The imbalance lead that we can't observe polyT at R1, but the reads for barcode, UMI and gene body after QC are sufficient for downstream analysis.

Best
Ran
